name: Sync upstream

on:
  schedule:
    - cron: '0 0 * * *' # Run at 00:00 UTC every day
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # all
      - name: sync
        run: |
          git config --global user.email "gh-actions[bot]@users.noreply.github.com"
          git config --global user.name "gh-actions[bot]"
          git remote add upstream "https://github.com/FIRST-Tech-Challenge/FTCRobotController.git"
          git fetch upstream
      - name: check
        run: |
          export UPSTREAM_UPDATES=$(git rev-list upstream/master --not HEAD --count)
          echo "There are $UPSTREAM_UPDATES updates from upstream"
      - name: prepare
        if: ${{ env.UPSTREAM_UPDATES > 0 }}
        run: |
          export BRANCH_NAME="latest-upstream"
          git switch -c $BRANCH_NAME || git switch $BRANCH_NAME
          git reset upstream/master
          git push --set-upstream origin $BRANCH_NAME
      - name: create PR
        if: ${{ env.UPSTREAM_UPDATES > 0 }}
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Sync upstream"
          title: "Sync upstream"
          body: "Sync upstream"
          branch: ${{ env.BRANCH_NAME }}
          base: master
          labels: |
            sync
